### PR TITLE
fix link (this is not markdown!)

### PR DESCRIPTION
**Pull request by dsyme**

### CODE REVIEW

**Comment by eiriktsarpalis** [comment]
Thanks!

**Comment by dsyme** [comment]
Don't forget to regenerate http://www.m-brace.net/ :) thanks!

**Comment by eiriktsarpalis** [comment]
Done!

**Comment by dsyme** [comment]
Strangely it doesn't seem to have updated that link, at least not yet for me

**Comment by dsyme** [comment]
Also the photos of Nick and Kostas seem to be have been reverted?

**Comment by eiriktsarpalis** [comment]
Oops. This is what happens when you forget to sync :)

**Pull request merged**
